version: '3'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      TZ: Africa/Kigali
    restart: always
    ports:
      - 8081:80
    networks:
      - my-network

  database:
    container_name: database
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_DATABASE: users
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      TZ: Africa/Kigali
    ports:
      - 8010:3306
    volumes:
      - ./mysql:/var/lib/mysql
      - ./db:/db
    networks:
      - my-network

  myapp:
    container_name: myapp
    restart: always
    build:
      context: .
    ports:
      - '8001:3000'
    volumes:
      - .:/app
    depends_on:
      - database
      - phpmyadmin
    environment: 
      TZ: Africa/Kigali
    command: npm run dev
    networks:
      - my-network

networks:
  my-network:
